name: Checks

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs
          mongodb-port: 27017
      - name: Lint and Test
        working-directory: ${{ matrix.dir }}
        run: |
          export MONGO_DBNAME=db
          export MONGO_URL=mongodb://localhost:27017
          go get .
          go mod tidy
          go test
